#!/usr/bin/expect
set program "P4.4"
set msg "Enter 3 parameters in format file-num1-num2: "
log_user 0
spawn $program
log_user 1
set f [open "test4"]
set commands [split [read $f] "\n"]
close $f
foreach cmd $commands {
    if { $cmd != "" } {
        expect {
            $msg
        }
        send "$cmd\n"
    }
}
expect {
    $msg
}
send 
expect *
puts $expect_out(buffer)
